"BEGIN basics
colorscheme onehalflight-benjamin
set exrc "allows local .vimrc in directory
if has("gui_running")
  set lines=80 columns=102
endif
set statusline=[%n]\ %t
set guifont=Monospace\ 11
set clipboard=unnamedplus
set scrolloff=3
set showcmd
set whichwrap+=<,>,h,l,[,]
set tabstop=4
set shiftwidth=4
let g:tex_comment_nospell=1 "deactivate spell checking in TeX comments
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
filetype plugin indent on
"END basics

"BEGIN save with ctrl-s
noremap <silent> <C-S> :w<CR>
inoremap <silent> <C-S> <C-O>:w<CR>
vnoremap <silent> <C-S> <Esc>:w<CR>gv
"END save with ctrl-s

"BEGIN line numbers
set number relativenumber
autocmd BufEnter,FocusGained,InsertLeave,WinEnter,CmdwinEnter * if &nu | set rnu   | endif
autocmd BufLeave,FocusLost,InsertEnter,WinLeave,CmdwinLeave   * if &nu | set nornu | endif
"END line numbers

"BEGIN word wrapping
set wrap
set linebreak
set nolist 
set textwidth=0
set wrapmargin=0
set formatoptions-=t
"END word wrapping

"BEGIN search settings
set incsearch
set ignorecase
set smartcase
highlight IncSearch ctermbg=green 
"END search settings

"BEGIN move efficiently between buffers
nnoremap <C-k> :bnext<CR>;
nnoremap <C-j> :bprevious<CR>;
nnoremap <C-l> :ls<CR>
nnoremap <C-h> :buffer<Space>
"END move efficiently between buffers

"BEGIN automatically open quickfix window after grep
augroup myvimrc
    autocmd!
    autocmd QuickFixCmdPost [^l]* cwindow
    autocmd QuickFixCmdPost l*    lwindow
augroup END
"END automatically open quickfix window after grep

"BEGIN path
let &path.="/usr/include/c++/5,/usr/include/x86_64-linux-gnu/c++/5,/usr/include/c++/5/backward,/usr/lib/gcc/x86_64-linux-gnu/5/include,/usr/local/include,/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed,/usr/include/x86_64-linux-gnu,/usr/include,"
"END path

call plug#begin('~/.vim/plugged')

Plug 'easymotion/vim-easymotion'
Plug 'kien/ctrlp.vim'
Plug 'lervag/vimtex'
Plug 'scrooloose/nerdcommenter'

call plug#end()

"BEGIN EasyMotion
map <Space> <Plug>(easymotion-s)
let g:EasyMotion_smartcase = 1
"END EasyMotion

"BEGIN NERD Commenter (It seems NERDCommenterToggle cannot be set to 'Ctrl + /', which would normally be done via <C-_>, but gVim recognizes 'Ctrl + /' as just '/'.)
map <C-c> <Plug>NERDCommenterToggle
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = -2
"END NERD Commenter

"BEGIN ctrlp
let g:ctrlp_custom_ignore = {
    \ 'dir': '\.git$\|build',
    \ 'file': '\v(\.cpp|\.cc|\.c|\.h|\.hpp|\.hh|\.cxx|\.tex|\.bib|\.txt|\.spthy|\.m4|\.m4i|\.rc|\.gpp|\.sh|\.xml|\.html|\.py|\.json|\.hs|\.md|\.m|\.cnf|Makefile)@<!$'
    \ }
"END ctrlp

"BEGIN vimtex
let g:vimtex_view_method = 'general'
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_view_forward_search_on_start = 0
let g:vimtex_quickfix_autojump = 0
let g:vimtex_quickfix_open_on_warning = 0
let g:bgrtex_quickfix_autojump = 1
"END vimtex
