"BEGIN basics
colorscheme onehalflight-benjamin
set exrc "allows local .vimrc in directory
if has("gui_running")
  set lines=80 columns=102
endif
set visualbell
set statusline=[%n]\ %t
set clipboard=unnamedplus
set scrolloff=3
set showcmd
set whichwrap+=<,>,h,l,[,]
set tabstop=4
set shiftwidth=4
let g:tex_comment_nospell=1 "deactivate spell checking in TeX comments
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
filetype plugin indent on
"END basics

"BEGIN save with ctrl-s
noremap <silent> <C-S> :w<CR>
inoremap <silent> <C-S> <C-O>:w<CR>
vnoremap <silent> <C-S> <Esc>:w<CR>gv
"END save with ctrl-s

"BEGIN line numbers
set number relativenumber
autocmd BufEnter,FocusGained,InsertLeave,WinEnter,CmdwinEnter * if &nu | set rnu   | endif
autocmd BufLeave,FocusLost,InsertEnter,WinLeave,CmdwinLeave   * if &nu | set nornu | endif
"END line numbers

"BEGIN word wrapping
set wrap
set linebreak
set nolist 
set textwidth=0
set wrapmargin=0
set formatoptions-=t
"END word wrapping

"BEGIN search settings
set incsearch
set ignorecase
set smartcase
highlight IncSearch ctermbg=green 
"END search settings

"BEGIN move efficiently between buffers
nnoremap <C-k> :bnext<CR>;
nnoremap <C-j> :bprevious<CR>;
nnoremap <C-l> :ls<CR>
nnoremap <C-h> :buffer<Space>
"END move efficiently between buffers

"BEGIN automatically open quickfix window after grep
augroup myvimrc
    autocmd!
    autocmd QuickFixCmdPost [^l]* cwindow
    autocmd QuickFixCmdPost l*    lwindow
augroup END
"END automatically open quickfix window after grep

"BEGIN astyle
map <C-a> :%!~/.vim/astyle-google --style=linux --indent=spaces=2<Enter>
"END astyle

"BEGIN path
let &path.="/usr/include/c++/5,/usr/include/x86_64-linux-gnu/c++/5,/usr/include/c++/5/backward,/usr/lib/gcc/x86_64-linux-gnu/5/include,/usr/local/include,/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed,/usr/include/x86_64-linux-gnu,/usr/include,"
"END path

call plug#begin('~/.vim/plugged')

Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdcommenter'
Plug 'kien/ctrlp.vim'
Plug 'vim-syntastic/syntastic'

call plug#end()

"BEGIN EasyMotion
map <Space> <Plug>(easymotion-s)
let g:EasyMotion_smartcase = 1
"END EasyMotion

"BEGIN NERD Commenter
"map <C-c> <Plug>NERDCommenterComment
map <C-x> <Plug>NERDCommenterUncomment
map <C-c> <Plug>NERDCommenterToggle
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = -2
"END NERD Commenter

"BEGIN ctrlp
let g:ctrlp_custom_ignore = {
    \ 'dir': '\.git$\|build',
    \ 'file': '\v(\.cpp|\.cc|\.c|\.h|\.hpp|\.hh|\.cxx|\.tex|\.bib|\.txt|\.spthy|\.m4|\.m4i|\.rc|\.gpp|\.sh|\.xml|\.html|\.py|\.json|\.hs|\.md|Makefile)@<!$'
    \ }
"END ctrlp

"BEGIN Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_tex_checkers = []
let g:syntastic_cpp_include_dirs = [ '../include', 'include' ]
let g:syntastic_c_include_dirs = [ '../include', 'include' ]
let g:syntastic_cpp_checkers = ['gcc']
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_aggregate_erros = 1
"END Syntastic
